name: Sync Document to Aliyun OSS

on:
  push:
    branches:
      - main

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Sync latest docs to Aliyun OSS
        # 使用 s3-compatible-action，版本号为 v6
        uses: michaelliao/sync-s3-compatible-action@v6
        
        # Action 的参数通过 'env' 来设置，而不是 'with'
        env:
          # --- 必填参数 ---
          # 存储提供商类型：aliyun
          SYNC_TYPE: aliyun
          
          # 你的 OSS Bucket 名称
          SYNC_BUCKET: xyp-test-github
          
          # 你的 OSS Region
          SYNC_REGION: cn-beijing
          
          # OSS Access ID，从 Secrets 中获取
          SYNC_ACCESS_ID: ${{ secrets.AccessKeyId }}
          
          # OSS Access Secret，从 Secrets 中获取
          SYNC_ACCESS_SECRET: ${{ secrets.AccessKeySecret }}
          
          # --- 可选参数 ---
          # 指定需要同步的本地目录，'.' 表示整个仓库
          # 如果你的文档都在 'docs/' 目录下，这里可以设置为 'docs/'
          SYNC_DIR: .
          
          # 当本地没有，但 OSS 上有的文件，如何处理：
          # 'keep' (默认)：保留；'delete'：删除
          # 根据你的需求，如果你想保持 OSS 上的文件和 GitHub 仓库完全一致，可以设置为 'delete'
          SYNC_OPT_UNUSED: keep
